# Generated code do not commit.
file(TO_CMAKE_PATH "/home/niko/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/niko/ShonenX_iOS" PROJECT_DIR)

set(FLUTTER_VERSION "2.1.2+4" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 2 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 2 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 4 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/niko/flutter"
  "PROJECT_DIR=/home/niko/ShonenX_iOS"
  "DART_DEFINES=RkxVVFRFUl9CVUlMRF9OQU1FPTIuMS4y,RkxVVFRFUl9CVUlMRF9OVU1CRVI9NA==,RkxVVFRFUl9WRVJTSU9OPTMuNDcuMA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NGNmMjQxNjQyNg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NWY3NzYyNTY3Mw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy4w"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=true"
  "PACKAGE_CONFIG=/home/niko/ShonenX_iOS/.dart_tool/package_config.json"
  "FLUTTER_TARGET=lib/main.dart"
)
